package com.apimongo.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.apimongo.model.comentarios.Comentario;
import com.apimongo.model.comentarios.ComentarioRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
                // jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/comentarioak") // This means URL's start with /demo (after Application path)
public class ComentarioController {
    @Autowired // This means to get the bean called umeaRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ComentarioRepository comentarioRepository;

    @GetMapping(path = "/comentarioGuztiak")
    public @ResponseBody List<Comentario> allComments(){
        return comentarioRepository.allComments();
    }
    @PostMapping(path = "/comentarioBerria")
    public void newComment(@RequestParam String user,@RequestParam String filtro, @RequestParam String comentario  ){
    Comentario coment = new Comentario(user, filtro, comentario);
    comentarioRepository.newComment(coment);    
    }
}
