package com.apimongo.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.apimongo.model.inkesta.Inkesta;
import com.apimongo.model.inkesta.InkestaRepository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
                // jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/inkestak") // This means URL's start with /demo (after Application path)
public class InkestaController {
    @Autowired // This means to get the bean called umeaRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private InkestaRepository inkestaRepository;

    @GetMapping(path = "/inkestaGuztiak")
    public @ResponseBody List<Inkesta> allInkesta(){
        return inkestaRepository.allInkesta();
    }
    @PostMapping(path = "/inkestaBerria")
    public void newComment(@RequestParam String user,@RequestParam int question1,@RequestParam int question2,@RequestParam int question3,@RequestParam int question4  ){
    Inkesta inkesta = new Inkesta(user,question1,question2,question3,question4);
    inkestaRepository.newInkesta(inkesta);    
    }
}
