package com.apimongo.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.apimongo.model.partida_t3.PartidaT3;
import com.apimongo.model.partida_t3.PartidakT3Repository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/partidak_t3") // This means URL's start with /demo (after Application path)
public class PartidakT3Controller {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private PartidakT3Repository partidaRepository;

	@GetMapping(path = "/partidaGuztiak")
	public @ResponseBody List<PartidaT3> partidakAll() {
		// This returns a JSON or XML with the users
		return partidaRepository.findAll();
	}

	@GetMapping(path = "/partidaOnenak")
	public @ResponseBody List<PartidaT3> bestPartidakT3() {
		return partidaRepository.bestGames();
	}

	@GetMapping(path = "/partidaOkerrenak")
	public @ResponseBody List<PartidaT3> worsePartidakT3() {
		return partidaRepository.worseGames();
	}

	// Añadido por Iker Test
	@PostMapping(path = "/partidaGehitu")
	public void newPartida(@RequestParam String user, @RequestParam String data, @RequestParam int puntuazioa) {
		PartidaT3 partidaT3 = new PartidaT3(user, data, puntuazioa);
		partidaRepository.newPartida(partidaT3);
	}
}
