package com.apimongo.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.apimongo.model.partida_t4.PartidaT4;
import com.apimongo.model.partida_t4.PartidakT4Repository;

@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
@RequestMapping(path = "/partidak_t4") // This means URL's start with /demo (after Application path)
public class PartidakT4Controller {
	@Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
	private PartidakT4Repository partidaRepository;
    @GetMapping(path = "/partidaGuztiak")
	public @ResponseBody List<PartidaT4> partidakAll() {
		// This returns a JSON or XML with the users
		return partidaRepository.findAll();
	}
	@GetMapping(path = "/partidaOnenak")
	public @ResponseBody List<PartidaT4> bestPartidakT4(){
		return partidaRepository.bestGames();
	}
	@GetMapping(path = "/partidaOkerrenak")
	public @ResponseBody List<PartidaT4> worsePartidakT4(){
		return partidaRepository.worseGames();
	}
	//Añadido por Iker Test
	@PostMapping(path = "/partidaGehitu")
	public void newPartida(@RequestParam String user, @RequestParam String data, @RequestParam int puntuazioa){
		PartidaT4 partidaT4 = new PartidaT4(user, data, puntuazioa);
		partidaRepository.newPartida(partidaT4);
	}
}
